[build]
  publish = "."

[[redirects]]
  from = "/downloads/*"
  to = "/downloads/:splat"
  status = 200

[[headers]]
  for = "/downloads/*.pdf"
  [headers.values]
    Content-Disposition = "attachment"
    Cache-Control = "no-cache"

[[headers]]
  for = "/downloads/*.odt"
  [headers.values]
    Content-Disposition = "attachment"
    Cache-Control = "no-cache"
